language: generic

branches:
  only:
    - master

os:
  - osx

osx_image:
  - xcode9.2
  - xcode8.3
  - xcode8

matrix:
  include:
    - env: BUILD_OPTIONS=""
    - env: BUILD_OPTIONS="--devel"
  fast_finish: true

before_install:
  - brew update

script:
  - travis_wait brew install Formula/emacs-plus.rb $BUILD_OPTIONS
  - brew test Formula/emacs-plus.rb